name: flutter_torrent_streamer_example
description: Movie Streamer
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_spinkit: "^4.1.2"
  google_sign_in: ^4.5.9
  diacritic: ^0.1.1
  http: ^0.12.2
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_core: ^0.7.0
  provider: ^4.3.3
  shared_preferences: ^0.5.8
  cached_network_image: ^2.2.0+1
  dio: ^3.0.9
  scoped_model: ^1.0.1
  flutter_rating_bar: ^3.0.1+1
  carousel_slider: ^2.2.1
  shimmer: ^1.1.1
  photo_view: ^0.10.2
  flutter_staggered_grid_view: ^0.3.0
  flutter_tags: ^0.4.9
  youtube_player_flutter: ^7.0.0+7
  share: ^0.6.5+4
  get_it: ^5.0.1
  google_fonts: ^1.1.0
  splashscreen: ^1.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_torrent_streamer:
    path: ../

flutter:
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
  uses-material-design: true
  assets:
    - assets/images/popcorn.gif
    - assets/images/help.jpg
    - assets/images/download.png
    - assets/images/dmovie.png
